import { REPO_PAGE_PATH_NAME, DEVELOPERS_PAGE_PATH_NAME,ERROR_PAGE_PATH_NAME } from "./pathNames";
import {
  DATE_FILTER_CONFIG,
  LANGUAGE_FILTER_CONFIG,
  SPOKEN_LANGUAGE_FILTER_CONFIG,
} from "./configToFilters";

export {
  REPO_PAGE_PATH_NAME,
  DEVELOPERS_PAGE_PATH_NAME,
  ERROR_PAGE_PATH_NAME,
  DATE_FILTER_CONFIG,
  LANGUAGE_FILTER_CONFIG,
  SPOKEN_LANGUAGE_FILTER_CONFIG,
};
